// Code generated by "stringer -type Lang -output lang_stringer_generated.go"; DO NOT EDIT.

package internal

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Lunknown-0]
	_ = x[Lgo-1]
	_ = x[Lpython-2]
}

const _Lang_name = "LunknownLgoLpython"

var _Lang_index = [...]uint8{0, 8, 11, 18}

func (i Lang) String() string {
	if i < 0 || i >= Lang(len(_Lang_index)-1) {
		return "Lang(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Lang_name[_Lang_index[i]:_Lang_index[i+1]]
}
